using Microsoft.Win32;using System.Drawing;using System.Drawing.Imaging;using System.Runtime.InteropServices;using System.Windows;using System.Windows.Controls;using System.Windows.Input;using System.Windows.Interop;using System.Windows.Media;using System.Windows.Media.Imaging;using System.Windows.Shapes;using Forms=System.Windows.Forms;using Point=System.Windows.Point;using Rectangle=System.Windows.Shapes.Rectangle;
namespace ChichiCapture;
public partial class MainWindow:Window{
 enum Tool{Select,Crop,Pen,Arrow,Rectangle,Ellipse,Text,Mosaic} Tool tool;Point start;Shape? preview;Polyline? stroke;BitmapSource? source;readonly AppSettings settings=AppSettings.Load();readonly Forms.NotifyIcon tray;HwndSource? hookSource;bool exiting;const int HK=1,WM_HOTKEY=0x0312,ALT=1,CTRL=2,SHIFT=4;
 [DllImport("user32.dll")]static extern bool RegisterHotKey(IntPtr h,int id,uint mods,uint key);[DllImport("user32.dll")]static extern bool UnregisterHotKey(IntPtr h,int id);
 public MainWindow(){InitializeComponent();tray=new Forms.NotifyIcon{Icon=SystemIcons.Application,Text="ChichiCapture",Visible=true};var menu=new Forms.ContextMenuStrip();menu.Items.Add("영역 캡처",null,(_,_)=>Dispatcher.Invoke(BeginRegion));menu.Items.Add("창 캡처",null,(_,_)=>Dispatcher.Invoke(BeginWindow));menu.Items.Add("편집기 열기",null,(_,_)=>Dispatcher.Invoke(Restore));menu.Items.Add("종료",null,(_,_)=>Dispatcher.Invoke(Exit));tray.ContextMenuStrip=menu;tray.DoubleClick+=(_,_)=>Dispatcher.Invoke(Restore);Loaded+=(_,_)=>RegisterKey();Closing+=OnClosing;}
 void Restore(){Show();WindowState=WindowState.Normal;Activate();}void OnClosing(object? s,System.ComponentModel.CancelEventArgs e){if(!exiting){e.Cancel=true;Hide();tray.ShowBalloonTip(1000,"ChichiCapture","시스템 트레이에서 계속 실행됩니다.",Forms.ToolTipIcon.Info);}}void Exit(){exiting=true;Unregister();tray.Dispose();Application.Current.Shutdown();}
 void RegisterKey(){Unregister();var h=new WindowInteropHelper(this).Handle;uint m=(uint)((settings.Ctrl?CTRL:0)|(settings.Shift?SHIFT:0)|(settings.Alt?ALT:0));RegisterHotKey(h,HK,m,(uint)settings.HotKey);hookSource=HwndSource.FromHwnd(h);hookSource?.AddHook(Hook);StatusText.Text=$"영역 단축키: {(settings.Ctrl?"Ctrl+":"")}{(settings.Shift?"Shift+":"")}{(settings.Alt?"Alt+":"")}{(char)settings.HotKey}";}void Unregister(){var h=new WindowInteropHelper(this).Handle;if(h!=IntPtr.Zero)UnregisterHotKey(h,HK);if(hookSource!=null){hookSource.RemoveHook(Hook);hookSource=null;}}IntPtr Hook(IntPtr h,int m,IntPtr w,IntPtr l,ref bool done){if(m==WM_HOTKEY&&w.ToInt32()==HK){done=true;BeginRegion();}return IntPtr.Zero;}
 void RegionCapture_Click(object s,RoutedEventArgs e)=>BeginRegion();void WindowCapture_Click(object s,RoutedEventArgs e)=>BeginWindow();void BeginRegion(){Hide();Thread.Sleep(100);var p=new RegionWindow();if(p.ShowDialog()==true)Capture(p.Selection);else Restore();}void BeginWindow(){Hide();Thread.Sleep(100);var p=new WindowPicker();if(p.ShowDialog()==true)Capture(p.Selection);else Restore();}
 void Capture(Rect r){if(r.Width<2||r.Height<2){Restore();return;}using var bmp=new Bitmap((int)r.Width,(int)r.Height,PixelFormat.Format32bppArgb);using(var g=Graphics.FromImage(bmp))g.CopyFromScreen((int)r.X,(int)r.Y,0,0,bmp.Size);Restore();using var ms=new MemoryStream();bmp.Save(ms,ImageFormat.Png);ms.Position=0;var bi=new BitmapImage();bi.BeginInit();bi.CacheOption=BitmapCacheOption.OnLoad;bi.StreamSource=ms;bi.EndInit();bi.Freeze();SetSource(bi);AutoSave();}
 void SetSource(BitmapSource bi){source=bi;CaptureImage.Source=bi;Overlay.Children.Clear();Overlay.Width=EditorHost.Width=bi.PixelWidth;Overlay.Height=EditorHost.Height=bi.PixelHeight;StatusText.Text=$"캡처 완료: {bi.PixelWidth}×{bi.PixelHeight}";}System.Windows.Media.Brush CurrentBrush(){var i=(ComboBoxItem)ColorBox.SelectedItem;return (System.Windows.Media.Brush)new BrushConverter().ConvertFromString((string)i.Tag)!;}
 void SelectTool_Click(object s,RoutedEventArgs e)=>tool=Tool.Select;void CropTool_Click(object s,RoutedEventArgs e)=>tool=Tool.Crop;void PenTool_Click(object s,RoutedEventArgs e)=>tool=Tool.Pen;void ArrowTool_Click(object s,RoutedEventArgs e)=>tool=Tool.Arrow;void RectTool_Click(object s,RoutedEventArgs e)=>tool=Tool.Rectangle;void EllipseTool_Click(object s,RoutedEventArgs e)=>tool=Tool.Ellipse;void TextTool_Click(object s,RoutedEventArgs e)=>tool=Tool.Text;void MosaicTool_Click(object s,RoutedEventArgs e)=>tool=Tool.Mosaic;
 void Host_Down(object s,MouseButtonEventArgs e){if(source==null||tool==Tool.Select)return;start=e.GetPosition(Overlay);Overlay.CaptureMouse();var b=CurrentBrush();double t=StrokeSlider.Value;if(tool==Tool.Pen){stroke=new Polyline{Stroke=b,StrokeThickness=t,StrokeLineJoin=PenLineJoin.Round};stroke.Points.Add(start);Overlay.Children.Add(stroke);}else if(tool is Tool.Rectangle or Tool.Mosaic or Tool.Crop)preview=new Rectangle();else if(tool==Tool.Ellipse)preview=new Ellipse();else if(tool==Tool.Arrow)preview=new Line();else if(tool==Tool.Text){var x=Microsoft.VisualBasic.Interaction.InputBox("넣을 글자를 입력하세요.","텍스트");if(x.Length>0){var tb=new TextBlock{Text=x,Foreground=b,FontSize=Math.Max(16,t*5),FontWeight=FontWeights.Bold};Canvas.SetLeft(tb,start.X);Canvas.SetTop(tb,start.Y);Overlay.Children.Add(tb);}}if(preview!=null){preview.Stroke=b;preview.StrokeThickness=t;if(FillShape.IsChecked==true&&tool is Tool.Rectangle or Tool.Ellipse)preview.Fill=b;Overlay.Children.Add(preview);}}
 void Host_Move(object s,System.Windows.Input.MouseEventArgs e){if(e.LeftButton!=MouseButtonState.Pressed)return;var p=e.GetPosition(Overlay);if(stroke!=null){stroke.Points.Add(p);return;}if(preview is Line l){l.X1=start.X;l.Y1=start.Y;l.X2=p.X;l.Y2=p.Y;}else if(preview!=null){Canvas.SetLeft(preview,Math.Min(start.X,p.X));Canvas.SetTop(preview,Math.Min(start.Y,p.Y));preview.Width=Math.Abs(p.X-start.X);preview.Height=Math.Abs(p.Y-start.Y);}}
 void Host_Up(object s,MouseButtonEventArgs e){var p=e.GetPosition(Overlay);if(preview!=null&&(tool is Tool.Mosaic or Tool.Crop))Overlay.Children.Remove(preview);if(tool==Tool.Mosaic)Mosaic(start,p);else if(tool==Tool.Crop)Crop(start,p);else if(tool==Tool.Arrow&&preview is Line l)ArrowHead(l);preview=null;stroke=null;Overlay.ReleaseMouseCapture();}
 void ArrowHead(Line l){double a=Math.Atan2(l.Y2-l.Y1,l.X2-l.X1),n=16;Overlay.Children.Add(new Polygon{Fill=l.Stroke,Points=new PointCollection{new(l.X2,l.Y2),new(l.X2-n*Math.Cos(a-.45),l.Y2-n*Math.Sin(a-.45)),new(l.X2-n*Math.Cos(a+.45),l.Y2-n*Math.Sin(a+.45))}});}Int32Rect Sel(Point a,Point b){if(source==null)return Int32Rect.Empty;int x=(int)Math.Max(0,Math.Min(a.X,b.X)),y=(int)Math.Max(0,Math.Min(a.Y,b.Y)),w=(int)Math.Min(source.PixelWidth-x,Math.Abs(b.X-a.X)),h=(int)Math.Min(source.PixelHeight-y,Math.Abs(b.Y-a.Y));return w>1&&h>1?new Int32Rect(x,y,w,h):Int32Rect.Empty;}
 void Mosaic(Point a,Point b){var r=Sel(a,b);if(r.IsEmpty)return;var c=new CroppedBitmap(Render(),r);int w=Math.Max(1,r.Width/12),h=Math.Max(1,r.Height/12);var sm=new TransformedBitmap(c,new ScaleTransform((double)w/r.Width,(double)h/r.Height));var im=new System.Windows.Controls.Image{Source=sm,Width=r.Width,Height=r.Height,Stretch=Stretch.Fill};RenderOptions.SetBitmapScalingMode(im,BitmapScalingMode.NearestNeighbor);Canvas.SetLeft(im,r.X);Canvas.SetTop(im,r.Y);Overlay.Children.Add(im);}void Crop(Point a,Point b){var r=Sel(a,b);if(!r.IsEmpty)SetSource(new CroppedBitmap(Render(),r));}
 BitmapSource Render(){var z=new System.Windows.Size(EditorHost.Width,EditorHost.Height);EditorHost.Measure(z);EditorHost.Arrange(new Rect(z));var r=new RenderTargetBitmap((int)z.Width,(int)z.Height,96,96,PixelFormats.Pbgra32);r.Render(EditorHost);return r;}void Copy_Click(object s,RoutedEventArgs e){if(source!=null){Clipboard.SetImage(Render());StatusText.Text="클립보드에 복사했습니다.";}}void SavePng_Click(object s,RoutedEventArgs e){if(source==null)return;var d=new SaveFileDialog{Filter="PNG 이미지|*.png",InitialDirectory=settings.SaveFolder,FileName=Name()};if(d.ShowDialog()==true)Save(d.FileName);}void Save(string p){Directory.CreateDirectory(Path.GetDirectoryName(p)!);var e=new PngBitmapEncoder();e.Frames.Add(BitmapFrame.Create(Render()));using var f=File.Create(p);e.Save(f);StatusText.Text=$"저장: {p}";}string Name()=>$"Capture_{DateTime.Now:yyyy-MM-dd_HH-mm-ss}.png";void AutoSave(){if(settings.AutoSave&&source!=null)Save(Path.Combine(settings.SaveFolder,Name()));}void Settings_Click(object s,RoutedEventArgs e){var w=new SettingsWindow(settings){Owner=this};if(w.ShowDialog()==true){settings.Save();RegisterKey();}}
}
